#
# Module manifest for module 'PSPrettier'
#
# Generated by: Sam Erde
#
# Generated on: 8/1/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSPrettier.psm1'

# Version number of this module.
ModuleVersion = '0.0.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '667f8226-b454-41a2-96f0-779860a0f693'

# Author of this module
Author = 'Sam Erde'

# Company or vendor of this module
CompanyName = 'Sam Erde'

# Copyright statement for this module
Copyright = '(c) Sam Erde. All rights reserved.'

# Description of the functionality provided by this module
Description = 'A PowerShell module for formatting code using Prettier.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1.0'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Invoke-Prettier'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Prettier','Formatting','CrescendoBuilt'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/SamErde/PSPrettier/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/SamErde/PSPrettier'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'https://github.com/SamErde/PSPrettier/CHANGELOG.md'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

    } # End of PSData hashtable


    # CrescendoGenerated
    CrescendoGenerated = '08/01/2025 07:08:28'

    # CrescendoVersion
    CrescendoVersion = '1.1.0'

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
